# Use distribution Ubuntu 18.04 Bionic
dist: bionic

# Travis CI does install a virtual environment automatically for python 3.6
language: python

python:
    - "3.6"

# command to install dependencies
install:
    - sudo apt-get update -y
    - sudo apt-get install libenchant1c2a -y
    # Requirements for the software
    - pip install -r requirements.txt
    # Requirements to deploy the documentation
    - pip install sphinx_rtd_theme
    - pip install sphinxcontrib.spelling
    - pip install --upgrade recommonmark
    # Requirements to run tests
    - pip install flake8
    - pip install parameterized

# Addons necessary for documentation.
addons:
    apt:
        packages:
            - python3-sphinx

# command to run tests
before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)/src
script: 
    - flake8 src/
    - python3 -m unittest discover -s src --verbose
    #- make spelling
    #- make linkcheck
    - cd docs
    - sphinx-build -b html ./ ./build/
    - touch build/.nojekyll

deploy:
    provider: pages
    skip_cleanup: true
    local_dir: docs/build
    keep-history: true
    target_branch: gh-pages
    github_token: $GITHUB_TOKEN
    on:
        branch: master
